### ISSUE TITLE
with OS X 10.10.2 Continuity Activation Tool causes wifi-related problems

### ISSUE THREAD

**Issue by fabiocip89** [dokterdok/Continuity-Activation-Tool#136]
OS X 10.10.2 is out and now wifi works fine, but installing the latest beta before the official release Wi-Fi no longer had those issues that everyone was complaining about. anyway, since the update changed bluetooth and wifi kexts, I had to install again ACT and after this operation the wifi was broken again, bringing handoff to my old macbook, but taking my macbook back to the black hole of wi-fi slowness and giving-me-headache-ness. I guess the thing is that ACT actually works by replacing original kexts with patched one, so the solution to this problem could be patching the new kexts contained in the latest OS X 10.10.2 update!

**Comment by dokterdok** [comment]
Hello,
CAT always patches the current drivers, it doesn't install old ones. Any slowness issues you notice are likely related to the OS X drivers themselves or other factors than CAT, as discussed in previous issues.

**Comment by fabiocip89** [comment]
well, sorry for the bad thought. I actually didn't know how the tool worked, so that was only a guess of mine about the issues. well, I have installed now the official update and wi-fi works fine. if it happens something after i reinstall CAT I'll let you know, but know I'm confident there will be none. Thanks for the fast answer and for the great job done about continuity tool!

**Comment by dokterdok** [comment]
Thanks for the feedback fabio. I'll add a quick tip about using CAT after an OS X update, which may help avoid issues for other users who read this.

After applying an OS X update, and notice that Continuity got disabled by the update, it is not recommended to uninstall CAT. Why? Because OS X already uninstalled CAT by overwriting the wireless drivers with new, unpatched ones. Using the CAT uninstall feature at that moment will likely restore outdated drivers from an old CAT backup, therefore rolling back any wireless fixes and enhancements that the OS X update applied. Applying the CAT activation right after the upgrade (and overwriting any existing backups during the procedure) is the way to go, as it will apply a patch *on top* of the new, clean drivers.

As a rule of thumb: only use the uninstallation feature when you want to get rid of CAT.

Closing.
