### ISSUE TITLE
Yosemite 10.10.2 Update breaks BCM94331PCIEBT4CAX Support for MB Pro 17 (mid 2010)

### ISSUE THREAD

**Issue by hoinzy** [dokterdok/Continuity-Activation-Tool#141]
I had the Activationtool working with Apple Broadcom BCM94331PCIEBT4CAX in my MacBook Pro 17 Inch (Mid 2010), but after the Update I couldn't get it to work again even with reinstallation. I get the x cross on my WIFI logo in the menu bar. I did the manual method as described in http://forums.macrumors.com/showpost.php?p=20124161 before the Activation Tool existed, so I know the procedure. The Tool reports OK for everything after installation, and reports expected results also when doing diagnose without the patches applied. Seems like my combination of software and hardware is rather rare, since my wifi hardware only supplies two external antennas in comparison to newer Macbook revisions having 3. So one slot on the BCM94331PCIEBT4CAX was left unattached, without having major drawbacks in terms of speed or connectivity. Would be great to get this working again. Any files I could supply for bugtracking?

**Comment by dokterdok** [comment]
It seems something is wrong either with the Wi-Fi kext or the hardware. These symptoms can indicate a corrupt kext, possibly due to a manual hack combined with CAT. Your best bet is to be 100% sure that you have clean kexts installed and do the activation procedure again with the latest version of CAT.

Try this:

1. Rename any "KextBackup*" folders in your user directory, e.g. by adding _bak at the end
2. Proceed with the CAT uninstallation. Drivers from the OS X recovery drive will be re-installed.
3. Verify that you get Wi-Fi working again. If not, post your Wi-Fi drivers version by looking in >About This Mac>System Report>IO80211 Family. If it works continue.
4. Apply CAT, reboot, report back.

**Comment by spbriggs** [comment]
Same problem with MacBook Pro Mid 2010 15". Have restored numerous backups and tried CAT trunk and beta versions. Still no Continuity.

Wi-fi drivers version reports   IO80211 Family:	7.0 (700.52)

**Comment by spbriggs** [comment]
On closer inspection, this appears to be a Bluetooth issue so will open a separate issue.
