### ISSUE TITLE
unable to use beta

### ISSUE THREAD

**Issue by benedict6** [dokterdok/Continuity-Activation-Tool#144]
I'm trying to apply the fix from #111 which says to get CAT 2.0.1 beta. I've tried downloading the beta multiple times with different browsers, but when I run it, it says it's damaged and can't be opened.

**Comment by hrubymar10** [comment]
just run it from terminal (as like as me) or turn of GateKeeper

**Comment by benedict6** [comment]
Thank you, that worked (running from terminal). I thought it was actually damaged so I didn't want to run it, but I just googled "damaged" and see that this means "altered by something other than the developer".

**Comment by dokterdok** [comment]
I haven't code signed the beta with my developer certificate, which is why you get the "damaged" file error. The code hasn't been altered by a third party. You can actually see who uploaded changes to the beta code right [here](https://github.com/dokterdok/Continuity-Activation-Tool/commits/beta). 
I'd recommend @hrubymar10's suggestions as well.
Closing.
