### ISSUE TITLE
compatibility chart is incorrect

### ISSUE THREAD

**Issue by mdwoolweaver** [dokterdok/Continuity-Activation-Tool#173]
there is also a late 2011 MacBook Pro which is not mentioned for any of the MacBook Pro models

http://imgur.com/trBF2R4

**Comment by dokterdok** [comment]
You need to read the chart differently: The year label in the chart (e.g. *Late 2009*) defines the start of a color category. Just find out in which color category your Mac introduction date falls into. 

2011 MBP --> Lime category --> Works with a BT4.0 dongle or AirPort Express card.

I haven't included all existing dates variations intentionally, in order to declutter the chart.
