### ISSUE TITLE
OS X 10.11.2 Beta (15C27e) SIP Check Fail

### ISSUE THREAD

**Issue by hrubymar10** [dokterdok/Continuity-Activation-Tool#250]
--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

Select an option:

1) Activate Continuity	    4) Uninstall with Recovery
2) System Diagnostic	    5) Disable Auto Check App
3) Uninstall		    6) Quit
#? 2

--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBook5,2
Verifying Mac board-id...               OK. Short board id detected: Mac-F22788AA
Verifying OS X version...               Warning: This version of Mac OS X (10.11.2) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          NOT OK. Your hardware doesn't support Bluetooth 4.0, necessary for Continuity. Current LMP Version=4, expected 6.
Verifying Bluetooth features...         OK. Bluetooth features are currently not compatible with Continuity. This tool can try to fix this.
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v208 c518
Verifying Login Item...                 OK. Login item for Auto Continuity Check is not set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

Press any key to go back to the main menu...

--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

Select an option:

1) Activate Continuity	    4) Uninstall with Recovery
2) System Diagnostic	    5) Disable Auto Check App
3) Uninstall		    6) Quit
#? 1

--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

If you want to activate Continuity using a USB Bluetooth 4.0 dongle,
then unplug it and plug it in now. The script will continue once it is detected.

Press any key to continue without a USB Bluetooth 4.0 dongle...

--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

--- Initiating system compatibility check ---

Verifying SIP...                        OK
Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               Warning: This version of Mac OS X (10.11.2) is Experimental! Only partially tested on El Capitan
Are you sure you want to continue?
1) Yes
2) No
#? 1
Verifying Wi-Fi hardware...             OK
Verifying Bluetooth version...          OK
Verifying Bluetooth features...         OK
Verifying ContinuitySupport...          OK. This tool can fix this.
Verifying SIP...                        OK
To continue you need to disable System Integrity Protection and come back here.
1. Reboot and hold CMD + R
2. Utilities - Terminal
3. enter 'csrutil disable'
4. reboot
logout
-n Saving session...
-ne 
...copying shared history...
-ne 
...saving history...
-n truncating history files...
-ne 
...
completed.

[Process completed]

**Comment by pkayhart** [comment]
Your printout matches my experience. 

csrutil status gives status as disabled.

CAT system diagnosis states SIP is already disabled. 

CAT Activate Continuity option determines SIP is still enabled. I would think erroneously.

 


Paul M. Kayhart

     The Studio
pkayhart@gmail.com
(404) 379 - 4310

**Comment by pkayhart** [comment]
Tried again several times after re-boots and other such nominal things. Thought I should include terminal output.
MacBook Pro (15-inch, Early 2011)



--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

--- Initiating system compatiblity check ---

--- Hardware/OS checks ---
Verifying Continuity status...          OK. OS X reports Continuity as inactive
Verifying Mac model reference...        OK. Known compatible Mac Model detected: MacBookPro8,2
Verifying Mac board-id...               OK. Long board id detected: Mac-94245A3940C91C80
Verifying OS X version...               Warning: This version of Mac OS X (10.11.2) is Experimental! Only partially tested on El Capitan
Verifying Wi-Fi hardware...             OK. A Broadcom AirPort card is active, and uses the legacy Brcm4331 kext. This tool can fix this.
Verifying AWDL status...                OK. No AWDL is active, but the hardware seems to be able to support it. This tool can try to fix this.
Verifying Bluetooth hardware...         OK. The internal Bluetooth card is active
Verifying Bluetooth version...          OK. Bluetooth 4.0 detected
Verifying Bluetooth features...         OK. Bluetooth features are Continuity compliant
Verifying Bluetooth firmware...         OK. Bluetooth firmware version: v151 c5844
Verifying Login Item...                 osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.
OK. Login item for Auto Continuity Check is set.

--- Modifications check ---
Verifying OS kext protection...         OK. Kext developer mode is already active
Verifying SIP...                        Ok. System Integrity Protection is already disabled
Verifying ContinuitySupport...          OK. Already patched.
Verifying kexts readability...          OK. Wi-Fi and Bluetooth kexts were found and could be read
Verifying Wi-Fi whitelist status...     OK. Your board-id is not yet whitelisted. This tool can fix this.
Verifying BT4 dongles compatibility...  OK. Compatibility with BT4 USB dongles is not enabled, this tool can fix this if a dongle is plugged in
Verifying old Wi-Fi kext presence...    OK. Legacy Brcm4331 Wi-Fi driver is present. This tool can fix this.
Verifying legacy Wi-Fi card patch...    OK. The legacy Wi-Fi patch is not present. This tool can fix this.
--- Modifications check ---

Press any key to go back to the main menu...1
--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              
Select an option:

1) Activate Continuity	    4) Uninstall with Recovery
2) System Diagnostic	    5) Disable Auto Check App
3) Uninstall		    6) Quit
#? 1


--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                              

If you want to activate Continuity using a USB Bluetooth 4.0 dongle,
then unplug it and plug it in now. The script will continue once it is detected.

Press any key to continue without a USB Bluetooth 4.0 dongle...



--- OS X Continuity Activation Tool 2.2.1 ---
                 by dokterdok                 
                                            
--- Initiating system compatibility check ---

Verifying SIP...                        OK
Verifying Mac model reference...        OK
Verifying Mac board-id...               OK
Verifying OS X version...               Warning: This version of Mac OS X (10.11.2) is Experimental! Only partially tested on El Capitan
Are you sure you want to continue?
1) Yes
2) No
#? 1
Verifying Wi-Fi hardware...             OK
Verifying Bluetooth version...          OK
Verifying Bluetooth features...         OK
Verifying ContinuitySupport...          OK. Already patched.
Verifying SIP...                        OK
To continue you need to disable System Integrity Protection and come back here.
1. Reboot and hold CMD + R
2. Utilities - Terminal
3. enter 'csrutil disable'
4. reboot
logout
-n Saving session...
-ne 
...copying shared history...
-ne 
...saving history...
-n truncating history files...
-ne 
...
completed.


Paul M. Kayhart

     The Studio
pkayhart@gmail.com
(404) 379 - 4310

**Comment by mike4047** [comment]
Same issue, same output. MacBookPro8,2
