### ISSUE TITLE
Windows Bluetooth

### ISSUE THREAD

**Issue by PerfectStory** [dokterdok/Continuity-Activation-Tool#265]
So this has been pissing me off recently, because it appeared I had fixed this issue outta dumb luck somehow and now I can't find out how to redo it. 

Basically I have a Late MBP 2011. I updated the bluetooth chip to the model shown in order to enable handoff on my OS X side which is "BCM94331PCIEBT4CAX"

When I go onto Windows, I try and pair my Magic Mouse 2 and it works, just I can't scroll at all. I've tried an installed the Magic Mouse 2 driver from the BC6 that I found on the internet and I've also installed my recommended BC5 supported by Windows 7, as well as removing the wireless mouse driver that was included in BC5 so there would be no driver error. 

Not sure what is causing this not to scroll, but works perfectly on OS X. Maybe someone else has found a solution.

**Comment by claywd1210** [comment]
This isn't a bluetooth issue or continuity issue. You would have more luck posting on a forum for bootcamp support. 

Since it is here though, uninstall and delete all the BootCamp Drivers from the system. Edit the install requirements if you have to but install the LATEST (possibly not Apple recommended) BootCamp System drivers. Only after this should you connect the magic mouse 2. If you have too, get a corded mouse to use in the meantime.

The driver itself isn't enough to give you scrolling, you need the updated BootCamp system drivers and system tray application to control the bluetooth options available from your magic mouse 2.

**Comment by claywd1210** [comment]
If your good, please close your issue.
